### ISSUE TITLE
Documentation - Demonstration in Vignette

### ISSUE THREAD

**Issue by micahkwok** [UBC-MDS/eda.utilsR#26]
Include a demonstration for each function in vignette:

- have a link to the demonstration in the README file

- [x] `imputer()`
- [x] `outlier_identifier()`
- [x] `cor_map()`
- [x] `scale()`

**Comment by fatse** [comment]
This was addressed in these PRs: https://github.com/UBC-MDS/eda.utilsR/pull/31 https://github.com/UBC-MDS/eda.utilsR/pull/39
